### ISSUE TITLE
Tomcat version was updated

### ISSUE THREAD

**Issue by alexove** [ramr/icescrum-openshift-quickstart#2]
Hello, I try your quickstar and fails, I notice that tomcat version was updated from 7.0.52 to 7.0.57, you might yo update this value too :-)

**Comment by ramr** [comment]
Thanks for the info. Sorry for the delay, for some reason I had no notification on this one. 
Fixed with  SHA: fa1fe94fa93b85b5d1ddc058913b357239c4fbf1  and SHA: 345160316869ba7158fd85a10e6bc6c4b0af3340
